### ISSUE TITLE
Design database

### ISSUE THREAD

**Issue by cronokirby** [Sharingang/Sharingang-Android#8]
See #5

**Comment by betrisey** [comment]
Firebase doesn't use a relational model, instead it only stores collections of documents.
The documents are very similar to JSON objects, it supports arrays, nested objects, numbers, strings [and more](https://firebase.google.com/docs/firestore/manage-data/data-types?hl=en).
We will have an `items` collection containing item documents with the attributs defined below.
![diagram](https://user-images.githubusercontent.com/1939395/110497572-de034b00-80f6-11eb-9d81-184e62b244d5.png)
In the future we will also have a `users` collection and each item will have the userID of its creator.
